development:
  adapter: mysql2
  database: address_application
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: address_application_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: address_application_production
  pool: 5
  timeout: 5000
